version: '3.9'
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./.env
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
